##############       Bonus        ###########

- name: Wait for system to load SSH service
  ansible.builtin.wait_for_connection:
    timeout: 30


- name: install Apache
  ansible.builtin.shell:
    cmd: |
      ssh -o StrictHostKeyChecking=no -i ~/.ssh/my_aws ec2-user@{{ my_instance_info.instances[0].public_ip_address }} '
      sudo yum install -y httpd &&
      sudo systemctl start httpd &&
      curl http://169.254.169.254/latest/meta-data/local-ipv4 | sudo tee /var/www/html/index.html'
